[package]
name = "ducktails"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
chrono = "0.4.45"
clap = { version = "4.6.6", features = ["derive"] }
datafusion = "55.0.0"
datafusion-datasource = "55.0.0"
glob = "0.3.4"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[dev-dependencies]
tempfile = "3"
